### ISSUE TITLE
Getting this unicodeEncode Error for few sites:

### ISSUE THREAD

**Issue by suri02** [Cmastris/robotstxt-change-monitor#2] opened 2021-02-16 08:48 UTC
Hi,

I tried to run few websites i'm getting the below error for 2 websites. Can anyone please help me on this how to resolve this.

16-02-21, 11:09: Error: https://www.example.com/. Unexpected error during https://www.example.com/ check.
TYPE: <class 'UnicodeEncodeError'>
DETAILS: 'charmap' codec can't encode character '\u0432' in position 3529: character maps to
TRACEBACK:

File "D:\Python\robots_txt\main.py", line 222, in run_check
self.update_records(extraction)
File "D:\Python\robots_txt\main.py", line 313, in update_records
new.write(new_extraction)
File "C:\Python34\lib\encodings\cp1252.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0]

Thank you,

**Comment by Cmastris** [comment] 2021-02-16 18:57
Hi @suri02, could you provide the specific URLs please so I can investigate/test the solution? 
https://www.example.com/robots.txt isn't a valid robots.txt file, but I'm guessing there's a valid site/file which isn't working too?

**Comment by suri02** [comment] 2021-02-17 04:34
> Hi @suri02, could you provide the specific URLs please so I can investigate/test the solution?
> https://www.example.com/robots.txt isn't a valid robots.txt file, but I'm guessing there's a valid site/file which isn't working too?

Hi @Cmastris 

Please find the attached error log file.

Thank you,

[log.txt](https://github.com/Cmastris/robotstxt-change-monitor/files/5993242/log.txt)

**Comment by Cmastris** [comment] 2021-02-17 20:05
Thanks @suri02 👍 

I've adjusted the file write so that if a character can't be encoded, it's replaced with an escape sequence instead ("backslashreplace", described in [the docs](https://docs.python.org/3/library/codecs.html#error-handlers)).

I've pushed a new version of [main.py](https://github.com/Cmastris/robotstxt-change-monitor/blob/main/main.py) to the repo; could you try using this and confirm if the issue is resolved? It seems to be working in my testing 🙂

**Comment by suri02** [comment] 2021-02-18 07:20
> Thanks @suri02 👍
> 
> I've adjusted the file write so that if a character can't be encoded, it's replaced with an escape sequence instead ("backslashreplace", described in [the docs](https://docs.python.org/3/library/codecs.html#error-handlers)).
> 
> I've pushed a new version of [main.py](https://github.com/Cmastris/robotstxt-change-monitor/blob/main/main.py) to the repo; could you try using this and confirm if the issue is resolved? It seems to be working in my testing 🙂

Hi @Cmastris 

Now it is working fine. Thanks a lot Chris for putting this all up here.

Thank you
Suri

**Comment by suri02** [comment] 2021-02-18 12:58
Hi @Cmastris 

I'm trying to automate the process by (**cron job implementation)** through task scheduler (**OS - Windows 10**). 
I created batch file instead of directly adding the python script in scheduler. Batch file contains path to **python.exe** (Application) and path to my "**main.py**" script. 
By manually running the batch file it is working correctly, but when i add that batch file as a program in task scheduler it is not working it is throwing the below error.

C:\windows\system32>C:\Users\suri02\AppData\Local\Programs\Python\Python39\python.exe "D:\Python Tasks\robots txt stuff\main.py"
Fatal error.
TYPE: <class 'FileNotFoundError'>
DETAILS: [Errno 2] No such file or directory: 'monitored_sites.csv'
TRACEBACK:

File "D:\Python Tasks\robots txt stuff\main.py", line 468, in main
    sites_data = sites_from_file(config.MONITORED_SITES)
  File "D:\Python Tasks\robots txt stuff\main.py", line 26, in sites_from_file
    with open(file, 'r') as sites_file:

Error when updating the main log.
TYPE: <class 'FileNotFoundError'>
DETAILS: [Errno 2] No such file or directory: 'data/main_log.txt'
TRACEBACK:

File "D:\Python Tasks\robots txt stuff\logs.py", line 86, in update_main_log
    with open(config.MAIN_LOG, 'a') as f:

**_Note: I don't have admin privileges to the system which i'm working on.'_**

Thanks
Suresh

**Comment by Cmastris** [comment] 2021-02-18 13:42
Hi @suri02 ,

Thanks for confirming- glad it's working now!

I've created a new issue for the cron job question and will close this one: https://github.com/Cmastris/robotstxt-change-monitor/issues/3.

**Closed by Cmastris** 2021-02-18 13:42 UTC
Labels: bug
